<?php

declare(strict_types=1);

namespace Deployer;

require 'recipe/laravel.php';

set('application', 'surreytuning');
set('repository', 'git@github.com:SnipsCoder/Surreytuning.git');
set('branch', 'master');
set('keep_releases', 5);

// Confirmed during cutover discovery — update if discovery differs.
set('php_fpm_service', 'php8.3-fpm');
set('app_runtime_user', 'user');          // php-fpm pool / site user that owns the code
set('app_url', 'https://tuning-portal.com');

set('shared_files', ['.env']);            // APP_KEY lives here — never regenerated by deploys
set('shared_dirs', ['storage']);
set('writable_dirs', ['bootstrap/cache', 'storage', 'storage/framework', 'storage/logs']);
set('writable_mode', 'chmod');

set('composer_options', '--no-dev --prefer-dist --optimize-autoloader --no-interaction --no-progress');

host('production')
    ->setHostname(getenv('DEPLOY_HOST') ?: 'srv1799606.hstgr.cloud')
    ->setRemoteUser('root')               // per server policy: root SSH, no sudo -u wrappers
    ->setDeployPath('/home/user/htdocs/tuning-portal');

/*
| Build tasks — run in the NEW release dir, before the symlink flips
*/

desc('Build front-end assets (Vite) in the release dir');
task('npm:build', function () {
    cd('{{release_path}}');
    run('npm ci --no-audit --no-fund', timeout: 900);
    run('npm run build', timeout: 900);
    run('rm -rf node_modules');           // build output lives in public/build
});

desc('Migrate the central database (forward-only)');
task('artisan:migrate:central', function () {
    cd('{{release_path}}');
    run('{{bin/php}} artisan migrate --force');
});

desc('Migrate every tenant database (forward-only, sequential)');
task('artisan:migrate:tenants', function () {
    cd('{{release_path}}');
    // stancl runs tenants one-by-one; on failure this task aborts the deploy
    // BEFORE the symlink flips — see runbook "When tenants:migrate fails".
    run('{{bin/php}} artisan tenants:migrate --force', timeout: 1800);
});

desc('Rebuild caches — route, event, view, then config LAST (canonical order)');
task('artisan:cache:rebuild', function () {
    cd('{{release_path}}');
    run('{{bin/php}} artisan route:cache');
    run('{{bin/php}} artisan event:cache');
    run('{{bin/php}} artisan view:cache');
    run('{{bin/php}} artisan config:cache');   // MUST be last — env() is dead after this
});

desc('Hand ownership of the release to the runtime user');
task('deploy:owner', function () {
    run('chown -R {{app_runtime_user}}:{{app_runtime_user}} {{release_path}}');
});

/*
| Post-flip tasks
*/

desc('Signal queue workers to restart onto the new code');
task('queue:restart-workers', function () {
    run('cd {{current_path}} && {{bin/php}} artisan queue:restart');
});

desc('Reload php-fpm to flush opcache/realpath cache');
task('php-fpm:reload', function () {
    run('systemctl reload {{php_fpm_service}}');
});

desc('Verify /healthz from outside, with retry/backoff');
task('healthcheck', function () {
    $token = getenv('HEALTH_CHECK_TOKEN') ?: '';
    if ($token === '') {
        // Fallback for rollbacks/deploys run from a dev machine without the secret:
        // read the token straight from the server's shared .env.
        $token = trim(run("grep -E '^HEALTH_CHECK_TOKEN=' {{deploy_path}}/shared/.env | cut -d= -f2- | tr -d '\"' || true"));
    }

    $url = get('app_url') . '/healthz' . ($token !== '' ? '?token=' . rawurlencode($token) : '');

    $delays = [5, 10, 15, 20, 30];        // seconds between attempts (6 attempts total)
    $attempt = 0;
    while (true) {
        $attempt++;
        $out = runLocally('curl -fsS --max-time 10 ' . escapeshellarg($url) . ' || true');
        if (str_contains($out, '"status":"ok"')) {
            info("healthz OK on attempt {$attempt}");
            return;
        }
        if ($attempt > count($delays)) {
            break;
        }
        $wait = $delays[$attempt - 1];
        warning("healthz not OK (attempt {$attempt}): {$out} — retrying in {$wait}s");
        sleep($wait);
    }

    // Alert-only policy: fail the deploy loudly; symlink stays on the new release.
    // Operator decides: forward-fix, or `dep rollback` (one command).
    throw new \RuntimeException(
        'Health check failed after retries. Site may be unhealthy. ' .
        'Inspect logs, then either forward-fix or run: dep rollback'
    );
});

/*
| Main deploy flow
| deploy:prepare = info + setup + lock + release + update_code + shared + writable.
| Everything through cache:rebuild happens in releases/<N>; `current` only
| flips at deploy:symlink, after migrations and caches succeeded.
*/

desc('Deploy surreytuning to production');
task('deploy', [
    'deploy:prepare',
    'deploy:vendors',            // composer install (composer_options above)
    'npm:build',
    'artisan:storage:link',
    'artisan:migrate:central',   // central FIRST...
    'artisan:migrate:tenants',   // ...then every tenant DB
    'artisan:cache:rebuild',
    'deploy:owner',
    'deploy:symlink',            // ← atomic flip; nothing above touched `current`
    'queue:restart-workers',
    'php-fpm:reload',
    'healthcheck',
    'deploy:unlock',
    'deploy:cleanup',            // prunes beyond keep_releases
    'deploy:success',
]);

after('deploy:failed', 'deploy:unlock');

// A rollback flips the symlink back — workers and opcache must follow it.
after('rollback', 'queue:restart-workers');
after('rollback', 'php-fpm:reload');
